/* ─── Segal Build — Core Categories (20 key categories) ─── */
import { cat, catX, type WorkCategory } from './types';

export const CORE_CATEGORIES: WorkCategory[] = [
  catX('bathroom', '🚿 Bathroom / Wet Areas', 'bathroom', 'wet', 'assembly',
    [{ id: 'size', label: 'Approximate size', type: 'select', options: ['Small (3x2m)', 'Medium (4x3m)', 'Large (5x3m)', 'Custom'] },
     { id: 'type', label: 'Type', type: 'select', options: ['Full renovation', 'New ensuite', 'New bathroom'] },
     { id: 'tileExtent', label: 'Wall tile extent', type: 'select', options: ['Shower only + skirting tile', '1200mm high walls', '2100mm high walls', 'Floor-to-ceiling walls'] },
     { id: 'tileFinish', label: 'Tile finish level', type: 'select', options: ['Standard ceramic', 'Rectified porcelain', 'Feature wall included', 'Large-format premium'] },
     { id: 'vanityType', label: 'Vanity configuration', type: 'select', options: ['Standard 600mm vanity', '900mm vanity', '1200mm double vanity', 'Custom joinery vanity'] },
     { id: 'fixtures', label: 'Fixture quality', type: 'select', options: ['Standard', 'Mid-range', 'Premium'] }],
    [
      { name: 'Demolition & Removal', trade: 'Demo', rate: 2800, unit: 'item', duration: 2, description: 'Strip bathroom, remove debris' },
      { name: 'Plumbing Rough-in', trade: 'Plumbing', rate: 3200, unit: 'allow', duration: 2, description: 'Rough-in new pipework' },
      { name: 'Waterproofing', trade: 'Waterproofing', rate: 185, unit: 'area', duration: 1, description: 'AS3740 compliant membrane' },
      { name: 'Wall Tiling', trade: 'Tiling', rate: 145, unit: 'area', duration: 3, description: 'Supply & install wall tiles' },
      { name: 'Floor Tiling', trade: 'Tiling', rate: 155, unit: 'area', duration: 2, description: 'Supply & install floor tiles' },
      { name: 'Electrical Fit-off', trade: 'Electrical', rate: 1200, unit: 'allow', duration: 1, description: 'Lights, exhaust, heated towel rail' },
      { name: 'Vanity & Mirror Install', trade: 'Carpentry', rate: 800, unit: 'item', duration: 1, description: 'Install vanity, mirror, accessories' },
      { name: 'Plumbing Fit-off', trade: 'Plumbing', rate: 2400, unit: 'allow', duration: 1, description: 'Tapware, shower, toilet install' },
      { name: 'Silicone & Finish', trade: 'Carpentry', rate: 350, unit: 'item', duration: 0.5, description: 'Seal all joints, final clean' },
    ],
    [
      { description: 'Tiles', allowance: 80, unit: '$/m²' },
      { description: 'Tapware Set', allowance: 800, unit: 'set' },
      { description: 'Vanity Unit', allowance: 1200, unit: 'item' },
      { description: 'Toilet Suite', allowance: 600, unit: 'item' },
      { description: 'Shower Screen', allowance: 900, unit: 'item' },
      { description: 'Bath (if applicable)', allowance: 1100, unit: 'item' },
    ],
    ['AS3740 waterproofing compliance', 'All labour and materials', 'Waste removal and disposal', 'Standard fixture installation', 'Silicone sealing to all joints'],
    ['Asbestos removal', 'Structural alterations', 'Council/permit fees', 'Engineer certification', 'Floor levelling if required'],
    [{ categoryId: 'cabinetry', type: 'suggested' }, { categoryId: 'flooring', type: 'suggested' }, { categoryId: 'painting', type: 'suggested' }],
    { dimensionMode: 'area', bundles: ['waterproofing', 'plumbing', 'tiling'], supportsPcItems: true, contingency: 10, workType: 'renovation' },
  ),

  cat('kitchen', '🍳 Kitchen', 'kitchen', 'wet',
    [{ id: 'size', label: 'Kitchen size', type: 'select', options: ['Small (3x2m)', 'Medium (4x3m)', 'Large (5x4m)', 'Custom'] },
     { id: 'type', label: 'Scope', type: 'select', options: ['Full renovation', 'New kitchen', 'Cabinet replacement'] },
     { id: 'benchtop', label: 'Benchtop', type: 'select', options: ['Laminate', 'Stone (Caesarstone)', 'Porcelain'] }],
    [
      { name: 'Demolition & Remove', trade: 'Demo', rate: 2200, unit: 'item', duration: 2, description: 'Strip existing kitchen' },
      { name: 'Plumbing/Electrical Rough-in', trade: 'Plumbing', rate: 2800, unit: 'allow', duration: 2, description: 'Relocate services' },
      { name: 'Plastering & Making Good', trade: 'Plastering', rate: 165, unit: 'area', duration: 2, description: 'Patch walls and ceilings' },
      { name: 'Cabinet Installation', trade: 'Carpentry', rate: 6500, unit: 'allow', duration: 3, description: 'Supply & install cabinetry' },
      { name: 'Benchtop Template & Install', trade: 'Carpentry', rate: 3500, unit: 'allow', duration: 2, description: 'Stone benchtop templating & install' },
      { name: 'Splashback Tiling', trade: 'Tiling', rate: 145, unit: 'area', duration: 1, description: 'Install splashback tiles' },
      { name: 'Plumbing/Electrical Fit-off', trade: 'Electrical', rate: 2200, unit: 'allow', duration: 1, description: 'Connect appliances, lighting' },
      { name: 'Painting', trade: 'Painting', rate: 65, unit: 'area', duration: 2, description: 'Paint walls and ceilings' },
    ],
    [
      { description: 'Kitchen Cabinets', allowance: 8000, unit: 'allowance' },
      { description: 'Stone Benchtop', allowance: 4000, unit: 'allowance' },
      { description: 'Sink & Tapware', allowance: 900, unit: 'set' },
      { description: 'Handles & Hardware', allowance: 300, unit: 'allowance' },
    ],
    ['Delivery & installation of cabinetry', 'Standard appliance connections', 'Splashback tiling', 'Making good walls and painting'],
    ['Appliance supply (unless PC)', 'Gas fitting if required', 'Structural alterations', 'Flooring replacement', 'Council/permit fees'],
    [{ categoryId: 'plumbing', type: 'auto' }, { categoryId: 'electrical', type: 'auto' }, { categoryId: 'painting', type: 'suggested' }, { categoryId: 'flooring', type: 'suggested' }],
  ),

  cat('laundry', '🧺 Laundry', 'laundry', 'wet',
    [{ id: 'size', label: 'Laundry size', type: 'select', options: ['Small (2x2m)', 'Medium (3x2m)', 'Large (3x3m)'] },
     { id: 'type', label: 'Scope', type: 'select', options: ['Full renovation', 'New laundry', 'Upgrade'] }],
    [
      { name: 'Demolition', trade: 'Demo', rate: 1200, unit: 'item', duration: 1, description: 'Remove existing laundry' },
      { name: 'Plumbing Rough-in', trade: 'Plumbing', rate: 1800, unit: 'allow', duration: 1, description: 'Rough-in new services' },
      { name: 'Waterproofing', trade: 'Waterproofing', rate: 185, unit: 'area', duration: 1, description: 'Membrane to floor' },
      { name: 'Floor & Wall Tiling', trade: 'Tiling', rate: 155, unit: 'area', duration: 2, description: 'Supply & install tiles' },
      { name: 'Cabinetry Install', trade: 'Carpentry', rate: 2500, unit: 'allow', duration: 1, description: 'Install laundry cabinets' },
      { name: 'Plumbing Fit-off', trade: 'Plumbing', rate: 1200, unit: 'allow', duration: 0.5, description: 'Connect tub, taps, trough' },
    ],
    [
      { description: 'Tub & Tapware', allowance: 500, unit: 'set' },
      { description: 'Cabinetry', allowance: 2000, unit: 'allowance' },
      { description: 'Tiles', allowance: 70, unit: '$/m²' },
    ],
    ['AS3740 waterproofing', 'Cabinetry supply & install', 'Plumbing connections'],
    ['Appliance supply', 'Structural work', 'Floor levelling'],
    [{ categoryId: 'waterproofing', type: 'auto' }, { categoryId: 'plumbing', type: 'auto' }, { categoryId: 'cabinetry', type: 'suggested' }],
    10, 'renovation',
  ),

  cat('flooring', '🪵 Flooring', 'flooring', 'wet',
    [{ id: 'type', label: 'Floor type', type: 'select', options: ['Timber', 'Tiles', 'Carpet', 'Vinyl', 'Polished Concrete'] },
     { id: 'area', label: 'Area', type: 'select', options: ['Single room', 'Multiple rooms', 'Whole house'] }],
    [
      { name: 'Subfloor Preparation', trade: 'Carpentry', rate: 55, unit: 'area', duration: 1, description: 'Level and prepare subfloor' },
      { name: 'Floor Installation', trade: 'Flooring', rate: 85, unit: 'area', duration: 3, description: 'Supply & install flooring' },
      { name: 'Skirting & Finishing', trade: 'Carpentry', rate: 35, unit: 'linear', duration: 1, description: 'Install skirting boards' },
    ],
    [
      { description: 'Floor Covering', allowance: 60, unit: '$/m²' },
      { description: 'Underlay', allowance: 15, unit: '$/m²' },
      { description: 'Skirting', allowance: 25, unit: '$/lm' },
    ],
    ['Subfloor preparation', 'Floor supply & installation', 'Skirting and finishing'],
    ['Furniture removal', 'Structural subfloor repairs', 'Asbestos removal'],
    [{ categoryId: 'demolition', type: 'suggested' }, { categoryId: 'painting', type: 'suggested' }],
    8, 'renovation',
  ),

  cat('painting', '🎨 Painting', 'painting', 'wet',
    [{ id: 'scope', label: 'Scope', type: 'select', options: ['Interior', 'Exterior', 'Both'] },
     { id: 'rooms', label: 'Number of rooms', type: 'number' }],
    [
      { name: 'Surface Preparation', trade: 'Painting', rate: 35, unit: 'area', duration: 2, description: 'Sand, fill, prime surfaces' },
      { name: 'Painting — Walls', trade: 'Painting', rate: 45, unit: 'area', duration: 2, description: 'Two coats interior walls' },
      { name: 'Painting — Trim', trade: 'Painting', rate: 35, unit: 'linear', duration: 1, description: 'Doors, windows, skirting' },
    ],
    [{ description: 'Paint (Dulux/Porter\'s)', allowance: 45, unit: '$/m²' }],
    ['Surface preparation and priming', 'Two coats quality paint', 'All labour and materials'],
    ['Wall repairs/plastering', 'Mould remediation', 'Wallpaper removal'],
    [{ categoryId: 'ceilings', type: 'suggested' }, { categoryId: 'internalWalls', type: 'suggested' }],
    5, 'maintenance',
  ),

  cat('demolition', '🏚️ Demolition', 'demolition', 'structural',
    [{ id: 'scope', label: 'Scope', type: 'select', options: ['Partial/internal', 'Full', 'Selective'] }],
    [
      { name: 'Demolition Works', trade: 'Demo', rate: 180, unit: 'area', duration: 2, description: 'Selective or full demolition' },
      { name: 'Waste Removal', trade: 'Demo', rate: 800, unit: 'item', duration: 1, description: 'Skip bin hire and tip fees' },
    ],
    [{ description: 'Skip Bin Hire', allowance: 500, unit: 'item' }, { description: 'Tip Fees', allowance: 300, unit: 'item' }],
    ['All labour and disposal', 'Site clean after demo'],
    ['Asbestos removal', 'Hazardous material disposal', 'Structural support during demo'],
    [{ categoryId: 'structural', type: 'suggested' }, { categoryId: 'waste', type: 'auto' }],
    10, 'renovation',
  ),

  cat('structural', '🏗️ Structural', 'structural', 'structural',
    [{ id: 'scope', label: 'Scope', type: 'select', options: ['Wall removal', 'Beam install', 'Lintel upgrade', 'Engineering'] }],
    [
      { name: 'Engineering Certification', trade: 'Structural', rate: 2500, unit: 'item', duration: 5, description: 'Structural engineer plans' },
      { name: 'Temporary Support', trade: 'Structural', rate: 1800, unit: 'item', duration: 1, description: 'Prop and support structure' },
      { name: 'Beam/Post Installation', trade: 'Structural', rate: 4500, unit: 'item', duration: 2, description: 'Install LVL/steel beam' },
      { name: 'Making Good', trade: 'Carpentry', rate: 1200, unit: 'item', duration: 2, description: 'Patch and make good' },
    ],
    [{ description: 'Steel/LVL Beam', allowance: 2000, unit: 'item' }],
    ['Engineer-certified installation', 'Temporary support', 'Making good'],
    ['Engineering fees (if separate)', 'Council permits', 'Asbestos'],
    [{ categoryId: 'demolition', type: 'auto' }, { categoryId: 'ceilings', type: 'suggested' }, { categoryId: 'internalWalls', type: 'suggested' }],
    15, 'structural',
  ),

  cat('decking', '🪵 Decking', 'decking', 'external',
    [{ id: 'size', label: 'Deck size', type: 'select', options: ['Small (3x3m)', 'Medium (4x4m)', 'Large (6x4m)', 'Custom'] },
     { id: 'material', label: 'Material', type: 'select', options: ['Timber (Merbau)', 'Composite', 'Treated Pine'] }],
    [
      { name: 'Site Preparation', trade: 'Carpentry', rate: 800, unit: 'item', duration: 1, description: 'Level and prep area' },
      { name: 'Subframe Construction', trade: 'Carpentry', rate: 120, unit: 'area', duration: 2, description: 'Bearers, joists, stumps' },
      { name: 'Deck Board Installation', trade: 'Carpentry', rate: 165, unit: 'area', duration: 2, description: 'Supply & fix deck boards' },
      { name: 'Stairs & Handrails', trade: 'Carpentry', rate: 450, unit: 'item', duration: 1, description: 'Construct stairs and rails' },
      { name: 'Sealing/Staining', trade: 'Carpentry', rate: 35, unit: 'area', duration: 0.5, description: 'Apply protective coating' },
    ],
    [{ description: 'Deck Boards (Merbau)', allowance: 120, unit: '$/m²' }, { description: 'Fasteners', allowance: 15, unit: '$/m²' }],
    ['H3/H4 treated subframe', 'Merbau or equivalent decking', 'Code-compliant handrails'],
    ['Council permits', 'Engineering certification (if >1m high)', 'Demolition of existing deck'],
    [{ categoryId: 'pergola', type: 'suggested' }, { categoryId: 'landscaping', type: 'suggested' }],
    8, 'new_build',
  ),

  catX('electrical', '⚡ Electrical', 'electrical', 'trades', 'trade',
    [{ id: 'scope', label: 'Scope of works', type: 'select', options: ['Switchboard upgrade', 'Rewire (whole house)', 'New install (room/area)', 'Lighting only', 'Additional points only'] }],
    [
      // Stage list kept as a fallback for legacy data — parametric items drive real pricing.
      { name: 'Rough-in (cabling)', trade: 'Electrical', rate: 0, unit: 'item', duration: 2, description: 'Run TPS through ceiling/wall cavities' },
      { name: 'Fit-off (devices)',  trade: 'Electrical', rate: 0, unit: 'item', duration: 1, description: 'Fit GPOs, switches, light fittings' },
      { name: 'Test & Certify',     trade: 'Electrical', rate: 0, unit: 'item', duration: 0.5, description: 'AS/NZS 3000 compliance certificate' },
    ],
    [], // No PC items on a pure trade — finishes are picked at the assembly that contains them.
    ['Licensed A-grade electrician', 'AS/NZS 3000 compliance certificate', 'All cabling and accessories'],
    ['Switchboard upgrade unless explicitly itemised', 'Solar / battery / EV charger', 'Smart-home programming', 'Patching & painting after chasing'],
    [],
    { dimensionMode: 'none', supportsPcItems: false, usesParametric: true, contingency: 5, workType: 'maintenance' },
  ),

  cat('plumbing', '🔧 Plumbing', 'plumbing', 'trades',
    [{ id: 'scope', label: 'Scope', type: 'select', options: ['Hot water', 'Sewer line', 'Stormwater', 'Gas fitting', 'Full re-plumb'] }],
    [
      { name: 'Rough-in', trade: 'Plumbing', rate: 2500, unit: 'allow', duration: 2, description: 'Run new pipework' },
      { name: 'Fit-off', trade: 'Plumbing', rate: 1800, unit: 'allow', duration: 1, description: 'Connect fixtures' },
      { name: 'Hot Water System', trade: 'Plumbing', rate: 2200, unit: 'item', duration: 1, description: 'Supply & install HWS' },
    ],
    [{ description: 'Hot Water System', allowance: 1800, unit: 'item' }, { description: 'Tapware', allowance: 250, unit: 'each' }],
    ['Licensed plumber', 'Compliance certificate', 'All materials'],
    ['Gas installation (separate licence)', 'Backflow prevention device', 'Council connections'],
    [],
    8, 'maintenance',
  ),

  cat('waterproofing', '💧 Waterproofing', 'waterproofing', 'trades',
    [{ id: 'area', label: 'Area', type: 'select', options: ['Shower', 'Bathroom', 'Balcony', 'Deck'] }],
    [
      { name: 'Surface Preparation', trade: 'Waterproofing', rate: 45, unit: 'area', duration: 0.5, description: 'Clean and prime surface' },
      { name: 'Membrane Application', trade: 'Waterproofing', rate: 120, unit: 'area', duration: 1, description: 'Apply AS3740 compliant membrane' },
      { name: 'Testing', trade: 'Waterproofing', rate: 350, unit: 'item', duration: 0.5, description: 'Flood test and certificate' },
    ],
    [{ description: 'Waterproofing Membrane', allowance: 65, unit: '$/m²' }],
    ['AS3740 compliance', 'Certificate of compliance', 'Flood test'],
    ['Making good surrounding areas', 'Drainage works', 'Tile removal'],
    [],
    5, 'renovation',
  ),

  cat('windowsDoors', '🪟 Windows & Doors', 'windowsDoors', 'external',
    [{ id: 'type', label: 'Scope', type: 'select', options: ['Replacement', 'New openings', 'Sliding doors', 'Stacker doors'] }],
    [
      { name: 'Remove Existing', trade: 'Demo', rate: 350, unit: 'item', duration: 0.5, description: 'Remove old window/door' },
      { name: 'Install New Unit', trade: 'Carpentry', rate: 850, unit: 'item', duration: 1, description: 'Supply & install new unit' },
      { name: 'Flash & Seal', trade: 'Carpentry', rate: 250, unit: 'item', duration: 0.5, description: 'Weatherproof installation' },
    ],
    [{ description: 'Window Unit', allowance: 800, unit: 'each' }, { description: 'Door Unit', allowance: 1500, unit: 'each' }],
    ['Supply and installation', 'Flashing and weatherproofing', 'Making good plaster'],
    ['Structural alterations to openings', 'Custom sizes (non-standard)', 'Engineering for new openings'],
    [{ categoryId: 'brickwork', type: 'suggested' }, { categoryId: 'painting', type: 'suggested' }],
    8, 'maintenance',
  ),

  cat('roofing', '🏠 Roofing — Re-Roof', 'roofing', 'external',
    [{ id: 'type', label: 'Roof type', type: 'select', options: ['Tile to Colorbond', 'Full re-roof tile', 'Full re-roof metal'] }],
    [
      { name: 'Strip Existing Roof', trade: 'Roofing', rate: 45, unit: 'area', duration: 2, description: 'Remove old roofing material' },
      { name: 'Sarking Installation', trade: 'Roofing', rate: 25, unit: 'area', duration: 1, description: 'Install reflective sarking' },
      { name: 'New Roof Installation', trade: 'Roofing', rate: 95, unit: 'area', duration: 3, description: 'Supply & install new roofing' },
    ],
    [{ description: 'Colorbond/Tile Roofing', allowance: 75, unit: '$/m²' }],
    ['Sarking and insulation', 'All flashings and ridge caps', 'Clean-up and disposal'],
    ['Structural timber replacement', 'Gutter/fascia (separate)', 'Insulation'],
    [{ categoryId: 'guttersFascia', type: 'suggested' }, { categoryId: 'roofRepairs', type: 'suggested' }, { categoryId: 'insulation', type: 'suggested' }],
    10, 'maintenance',
  ),

  cat('extensions', '🏠 Extensions', 'extensions', 'structural',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Single room', 'Multiple rooms', 'Ground floor extension'] },
     { id: 'size', label: 'Size', type: 'select', options: ['Small (3x4m)', 'Medium (4x5m)', 'Large (6x5m)', 'Custom'] }],
    [
      { name: 'Site Prep & Footings', trade: 'Concreting', rate: 8500, unit: 'item', duration: 3, description: 'Excavation, footings, slab' },
      { name: 'Frame & Lock-up', trade: 'Carpentry', rate: 12000, unit: 'item', duration: 4, description: 'Wall frame, roof, windows, door' },
      { name: 'Fit-out', trade: 'Carpentry', rate: 8000, unit: 'item', duration: 3, description: 'Plaster, linings, skirting' },
      { name: 'Trades', trade: 'Plumbing', rate: 5000, unit: 'item', duration: 3, description: 'Electrical, plumbing, HVAC' },
      { name: 'Finishes', trade: 'Painting', rate: 4500, unit: 'item', duration: 2, description: 'Paint, flooring, cleaning' },
    ],
    [{ description: 'Windows & Doors', allowance: 3000, unit: 'allowance' }, { description: 'Flooring', allowance: 2500, unit: 'allowance' }],
    ['Engineering included', 'Council permits (separate)', 'All labour and materials'],
    ['Council permit fees', 'Demolition of existing structure', 'Landscaping reinstatement'],
    [{ categoryId: 'structural', type: 'auto' }, { categoryId: 'concreting', type: 'auto' }, { categoryId: 'roofing', type: 'suggested' }],
    10, 'new_build',
  ),

  cat('fencing', '🏡 Fencing & Gates', 'fencing', 'external',
    [{ id: 'type', label: 'Fence type', type: 'select', options: ['Timber', 'Colorbond', 'Pool fencing', 'Retaining'] },
     { id: 'length', label: 'Length', type: 'select', options: ['Up to 10m', '10-20m', '20-40m', '40m+'] }],
    [
      { name: 'Post Installation', trade: 'Carpentry', rate: 85, unit: 'linear', duration: 1, description: 'Set posts in concrete' },
      { name: 'Panel/Infill Installation', trade: 'Carpentry', rate: 95, unit: 'linear', duration: 2, description: 'Install fence panels/infill' },
      { name: 'Gate Installation', trade: 'Carpentry', rate: 850, unit: 'item', duration: 1, description: 'Supply & install gate' },
    ],
    [{ description: 'Gate', allowance: 750, unit: 'each' }],
    ['All materials included', 'Post hole digging and concrete', 'Clean-up'],
    ['Retaining (separate)', 'Removing existing fence', 'Council permits for pool fencing'],
    [{ categoryId: 'landscaping', type: 'suggested' }, { categoryId: 'concreting', type: 'suggested' }],
    5, 'new_build',
  ),

  cat('concreting', '🧱 Concreting', 'concreting', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Slab', 'Path', 'Driveway', 'Patio'] }],
    [
      { name: 'Site Prep & Formwork', trade: 'Concreting', rate: 35, unit: 'area', duration: 1, description: 'Excavation, formwork, mesh' },
      { name: 'Pour & Finish', trade: 'Concreting', rate: 110, unit: 'area', duration: 1, description: 'Supply & pour concrete' },
    ],
    [],
    ['Formwork, reinforcement, pour, and finish', 'Standard broom/float finish'],
    ['Decorative finishes', 'Engineering for structural slabs', 'Drainage'],
    [{ categoryId: 'paving', type: 'suggested' }],
    5, 'new_build',
  ),

  cat('newHomeBuild', '🏡 New Home Build', 'newHomeBuild', 'structural',
    [{ id: 'size', label: 'Home size', type: 'select', options: ['Under 150m²', '150-250m²', '250-350m²', '350m²+'] },
     { id: 'storeys', label: 'Storeys', type: 'select', options: ['Single', 'Double'] }],
    [
      { name: 'Site & Foundation', trade: 'Concreting', rate: 45000, unit: 'item', duration: 4, description: 'Site cut, footings, slab' },
      { name: 'Frame & Roof', trade: 'Carpentry', rate: 65000, unit: 'item', duration: 4, description: 'Wall frame, roof structure, cladding' },
      { name: 'Lock-up', trade: 'Carpentry', rate: 35000, unit: 'item', duration: 3, description: 'Windows, doors, external complete' },
      { name: 'Fit-out', trade: 'Carpentry', rate: 45000, unit: 'item', duration: 5, description: 'Plaster, cabinetry, wet area fit-out' },
      { name: 'Trades', trade: 'Electrical', rate: 25000, unit: 'item', duration: 4, description: 'Electrical, plumbing, HVAC' },
      { name: 'Finishes', trade: 'Painting', rate: 20000, unit: 'item', duration: 3, description: 'Paint, flooring, final clean' },
    ],
    [{ description: 'Kitchen', allowance: 15000, unit: 'allowance' }, { description: 'Bathroom', allowance: 12000, unit: 'allowance' }, { description: 'Flooring', allowance: 10000, unit: 'allowance' }],
    ['Full construction to lock-up and completion', 'All trades included', 'Standard finishes throughout'],
    ['Council and building permit fees', 'Architect/engineer fees', 'Site survey', 'Landscaping', 'Driveway'],
    [{ categoryId: 'landscaping', type: 'suggested' }, { categoryId: 'paving', type: 'suggested' }, { categoryId: 'fencing', type: 'suggested' }],
    5, 'new_build',
  ),

  cat('hvac', '❄️ HVAC', 'hvac', 'trades',
    [{ id: 'type', label: 'System type', type: 'select', options: ['Split system', 'Ducted', 'Ventilation'] }],
    [
      { name: 'Supply & Install', trade: 'HVAC', rate: 3200, unit: 'item', duration: 1, description: 'Split system supply & install' },
    ],
    [{ description: 'Split System Unit', allowance: 2200, unit: 'each' }],
    ['Licensed HVAC technician', 'Compliance certificate'],
    ['Ducted system design', 'Electrical upgrades'],
    [],
    5, 'maintenance',
  ),

  cat('pergola', '🏡 Pergola & Patio', 'pergola', 'external',
    [{ id: 'size', label: 'Size', type: 'select', options: ['Small (3x3m)', 'Medium (4x3m)', 'Large (6x4m)'] },
     { id: 'type', label: 'Type', type: 'select', options: ['Freestanding', 'Attached', 'Flat roof', 'Gabled'] }],
    [
      { name: 'Footings', trade: 'Concreting', rate: 1500, unit: 'item', duration: 1, description: 'Concrete footings' },
      { name: 'Frame & Roof', trade: 'Carpentry', rate: 285, unit: 'area', duration: 3, description: 'Structure and roof' },
    ],
    [{ description: 'Roofing (Colorbond)', allowance: 65, unit: '$/m²' }],
    ['Engineered design', 'All materials and labour', 'Colour-matched to house'],
    ['Electrical (lighting/fans)', 'Screens/blinds', 'Concrete slab'],
    [{ categoryId: 'concreting', type: 'suggested' }, { categoryId: 'electrical', type: 'suggested' }, { categoryId: 'decking', type: 'suggested' }],
    8, 'new_build',
  ),

  cat('landscaping', '🌿 Landscaping', 'landscaping', 'external',
    [{ id: 'scope', label: 'Scope', type: 'select', options: ['Turf & garden', 'Full landscape', 'Retaining + planting'] }],
    [
      { name: 'Earthworks & Drainage', trade: 'Landscaping', rate: 65, unit: 'area', duration: 2, description: 'Grade, drain, prepare' },
      { name: 'Turf & Garden Beds', trade: 'Landscaping', rate: 55, unit: 'area', duration: 2, description: 'Lay turf, soil, plants' },
      { name: 'Irrigation', trade: 'Landscaping', rate: 2500, unit: 'item', duration: 1, description: 'Install irrigation system' },
    ],
    [{ description: 'Turf', allowance: 30, unit: '$/m²' }, { description: 'Plants', allowance: 1500, unit: 'allowance' }],
    ['Earthworks and soil preparation', 'Turf supply and laying', 'Basic irrigation'],
    ['Retaining walls', 'Paving/driveways', 'Irrigation design'],
    [{ categoryId: 'paving', type: 'suggested' }, { categoryId: 'retainingWalls', type: 'suggested' }, { categoryId: 'fencing', type: 'suggested' }],
    8, 'new_build',
  ),
];