/* ─── Segal Build — Extended Categories (remaining 23) ─── */
import { cat, catX, type WorkCategory } from './types';

export const EXTENDED_CATEGORIES: WorkCategory[] = [
  cat('toilet', '🚽 Toilet / WC', 'toilet', 'wet',
    [{ id: 'type', label: 'Type', type: 'select', options: ['New WC', 'Renovation', 'Relocation'] },
     { id: 'tileExtent', label: 'Wall tile extent', type: 'select', options: ['Skirting tile only', '1200mm high walls', '2100mm high walls', 'Floor-to-ceiling walls'] },
     { id: 'suiteType', label: 'Toilet suite type', type: 'select', options: ['Back-to-wall', 'Wall-hung', 'Standard close-coupled', 'In-wall cistern'] }],
    [{ name: 'Plumbing Rough-in', trade: 'Plumbing', rate: 1200, unit: 'allow', duration: 1, description: 'New drainage and water supply' },
     { name: 'Wall & Floor Prep', trade: 'Carpentry', rate: 800, unit: 'item', duration: 1, description: 'Stud frame, plasterboard' },
     { name: 'Tiling', trade: 'Tiling', rate: 155, unit: 'area', duration: 1, description: 'Wall and floor tiles' },
     { name: 'Fit-off', trade: 'Plumbing', rate: 600, unit: 'allow', duration: 0.5, description: 'Install toilet suite, cistern' }],
    [{ description: 'Toilet Suite', allowance: 500, unit: 'each' }, { description: 'Hand basin', allowance: 200, unit: 'each' }],
    ['Plumbing rough-in and fit-off', 'Tiling and waterproofing'],
    ['Structural alterations', 'Mechanical ventilation'],
    [{ categoryId: 'plumbing', type: 'auto' }, { categoryId: 'waterproofing', type: 'auto' }],
  ),

  cat('cabinetry', '🪟 Cabinetry & Joinery', 'cabinetry', 'wet',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Built-in robes', 'Shelving', 'Custom joinery', 'Entertainment unit'] }],
    [{ name: 'Design & Measure', trade: 'Carpentry', rate: 500, unit: 'item', duration: 1, description: 'Measure and design' },
     { name: 'Manufacture', trade: 'Carpentry', rate: 350, unit: 'linear', duration: 5, description: 'Custom manufacture' },
     { name: 'Installation', trade: 'Carpentry', rate: 180, unit: 'linear', duration: 2, description: 'Install and fit out' }],
    [{ description: 'Hardware', allowance: 200, unit: 'allowance' }],
    ['Custom design and manufacture', 'Installation and adjustment'],
    ['Electrical work within cabinetry', 'Appliance supply'],
    [],
  ),

  cat('ceilings', '🏠 Ceilings & Cornices', 'ceilings', 'structural',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Plasterboard repair', 'Bulkhead', 'Raking ceiling', 'New ceiling'] }],
    [{ name: 'Demolition (if req.)', trade: 'Demo', rate: 45, unit: 'area', duration: 1, description: 'Remove existing ceiling' },
     { name: 'Frame & Sheet', trade: 'Carpentry', rate: 85, unit: 'area', duration: 2, description: 'Ceiling frame and plasterboard' },
     { name: 'Cornice & Finish', trade: 'Carpentry', rate: 35, unit: 'linear', duration: 1, description: 'Cornice, set, and finish' }],
    [],
    ['All materials and labour', 'Cornice and finishing'],
    ['Insulation (separate)', 'Asbestos removal'],
    [{ categoryId: 'painting', type: 'suggested' }, { categoryId: 'insulation', type: 'suggested' }],
  ),

  catX('internalWalls', '🧱 Internal Walls', 'internalWalls', 'structural', 'element',
    [
      { id: 'wallType', label: 'Wall construction', type: 'select', options: [
        '90mm timber stud + plasterboard',
        '70mm timber stud + plasterboard',
        '64mm steel stud + plasterboard',
        '92mm steel stud + plasterboard',
        'Single brick (110mm)',
        'Double brick cavity (270mm)',
        'Hebel block (75mm)',
      ] },
      { id: 'finish', label: 'Plasterboard finish', type: 'select', options: ['Standard 10mm', 'Wet-area 10mm (CSR Wet)', 'Acoustic 13mm', 'Fire-rated 13mm'],
        dependsOn: { questionId: 'wallType', values: ['90mm timber stud + plasterboard', '70mm timber stud + plasterboard', '64mm steel stud + plasterboard', '92mm steel stud + plasterboard'] } },
      { id: 'insulation', label: 'Acoustic / thermal insulation', type: 'select', options: ['None', 'R2.0 acoustic batt', 'R2.5 thermal batt', 'R2.7 acoustic + thermal'] },
    ],
    [
      { name: 'Frame', trade: 'Carpentry', rate: 85, unit: 'area', duration: 1, description: 'Construct wall frame to specified type' },
      { name: 'Insulation install', trade: 'Carpentry', rate: 18, unit: 'area', duration: 0.5, description: 'Friction-fit batt insulation' },
      { name: 'Sheet & set', trade: 'Carpentry', rate: 65, unit: 'area', duration: 1, description: 'Plasterboard, set 3-coat finish' },
    ],
    [], // No PC items — paint and skirting belong to their own categories.
    ['Frame to specified construction', 'Plasterboard to nominated finish', '3-coat set ready for paint'],
    ['Painting (separate category)', 'Skirting / architrave (separate category)', 'Electrical chasing & make-good', 'Structural lintels / load-bearing modifications'],
    [{ categoryId: 'painting', type: 'suggested' }, { categoryId: 'electrical', type: 'suggested' }, { categoryId: 'insulation', type: 'suggested' }],
    { dimensionMode: 'wall', supportsPcItems: false, contingency: 10, workType: 'renovation' },
  ),

  cat('underpinning', '🏠 Underpinning', 'underpinning', 'structural',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Restumping', 'Underpinning', 'Slab repair'] }],
    [{ name: 'Engineering Assessment', trade: 'Structural', rate: 2500, unit: 'item', duration: 5, description: 'Engineer inspection and report' },
     { name: 'Underpinning Works', trade: 'Concreting', rate: 450, unit: 'linear', duration: 5, description: 'Excavate and pour new footings' },
     { name: 'Restumping', trade: 'Carpentry', rate: 350, unit: 'item', duration: 3, description: 'Replace stumps and relevel' }],
    [{ description: 'Engineering Report', allowance: 2000, unit: 'item' }],
    ['Engineering assessment', 'All labour and materials'],
    ['Internal making good', 'Plumbing adjustments'],
    [{ categoryId: 'structural', type: 'auto' }, { categoryId: 'concreting', type: 'auto' }],
    15, 'structural',
  ),

  cat('retainingWalls', '🧱 Retaining Walls', 'retainingWalls', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Timber sleeper', 'Concrete block', 'Besser block'] }],
    [{ name: 'Excavation & Drainage', trade: 'Landscaping', rate: 120, unit: 'linear', duration: 1, description: 'Excavate and install drainage' },
     { name: 'Wall Construction', trade: 'Carpentry', rate: 280, unit: 'linear', duration: 2, description: 'Build retaining wall' }],
    [],
    ['Drainage behind wall', 'All materials and labour'],
    ['Engineering for walls >1m', 'Council permits'],
    [{ categoryId: 'landscaping', type: 'suggested' }, { categoryId: 'concreting', type: 'suggested' }],
  ),

  cat('steelFraming', '🏗️ Steel & Framing', 'steelFraming', 'structural',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Steel beam', 'Timber framing', 'Steel posts'] }],
    [{ name: 'Engineering Design', trade: 'Structural', rate: 1800, unit: 'item', duration: 5, description: 'Engineer specify beam' },
     { name: 'Fabrication & Install', trade: 'Structural', rate: 3500, unit: 'item', duration: 2, description: 'Supply and install steel' }],
    [],
    ['Engineering certification', 'Supply and installation'],
    ['Crane hire if required', 'Making good'],
    [{ categoryId: 'structural', type: 'auto' }, { categoryId: 'demolition', type: 'suggested' }],
    15, 'structural',
  ),

  cat('secondStorey', '🏢 Upper Storey Extension', 'secondStorey', 'structural',
    [{ id: 'size', label: 'Size', type: 'select', options: ['Single room', 'Full upper storey extension'] }],
    [{ name: 'Engineering & Permits', trade: 'Structural', rate: 8000, unit: 'item', duration: 10, description: 'Engineer and council' },
     { name: 'Strengthening', trade: 'Structural', rate: 25000, unit: 'item', duration: 4, description: 'Strengthen existing structure' },
     { name: 'Upper Storey Construction', trade: 'Carpentry', rate: 85000, unit: 'item', duration: 8, description: 'Full upper storey extension build' }],
    [{ description: 'Staircase', allowance: 8000, unit: 'item' }],
    ['Engineering and permits', 'Structural strengthening', 'Full construction'],
    ['Temporary accommodation', 'Asbestos removal', 'Landscaping'],
    [{ categoryId: 'structural', type: 'auto' }, { categoryId: 'roofing', type: 'auto' }],
    15, 'new_build',
  ),

  cat('multiUnit', '🏘️ Multi-Unit', 'multiUnit', 'structural',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Dual occupancy', 'Townhouses', 'Triplex'] }],
    [{ name: 'Site Works & Foundation', trade: 'Concreting', rate: 80000, unit: 'item', duration: 4, description: 'Site cut, footings, slab' },
     { name: 'Construction', trade: 'Carpentry', rate: 250000, unit: 'item', duration: 12, description: 'Full multi-unit build' }],
    [],
    ['Multi-unit construction', 'All trades'],
    ['DA and CDC approvals', 'Architect fees', 'Landscaping'],
    [{ categoryId: 'newHomeBuild', type: 'suggested' }],
    10, 'new_build',
  ),

  cat('grannyFlat', '🏠 Granny Flat / DPU', 'grannyFlat', 'structural',
    [{ id: 'size', label: 'Size', type: 'select', options: ['1 bed (40-50m²)', '2 bed (60-70m²)'] }],
    [{ name: 'Site Prep & Slab', trade: 'Concreting', rate: 22000, unit: 'item', duration: 3, description: 'Site prep and slab' },
     { name: 'Frame to Lock-up', trade: 'Carpentry', rate: 45000, unit: 'item', duration: 4, description: 'Frame, roof, lock-up' },
     { name: 'Fit-out', trade: 'Carpentry', rate: 35000, unit: 'item', duration: 4, description: 'All finishes and trades' }],
    [{ description: 'Kitchen', allowance: 8000, unit: 'allowance' }, { description: 'Bathroom', allowance: 10000, unit: 'allowance' }],
    ['Complete granny flat construction', 'Kitchen and bathroom included'],
    ['DA/CDC approval', 'Utility connections', 'Landscaping'],
    [{ categoryId: 'newHomeBuild', type: 'suggested' }, { categoryId: 'landscaping', type: 'suggested' }],
    8, 'new_build',
  ),

  cat('paving', '🧱 Paving & Driveways', 'paving', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Concrete', 'Pavers', 'Exposed aggregate'] }],
    [{ name: 'Base Preparation', trade: 'Concreting', rate: 45, unit: 'area', duration: 1, description: 'Excavate, base, compact' },
     { name: 'Paving/Pour', trade: 'Concreting', rate: 95, unit: 'area', duration: 2, description: 'Lay pavers or pour concrete' }],
    [],
    ['Base preparation', 'Paving or concrete pour'],
    ['Drainage', 'Retaining walls'],
    [{ categoryId: 'concreting', type: 'suggested' }, { categoryId: 'landscaping', type: 'suggested' }],
  ),

  cat('pools', '🏊 Pool & Spa', 'pools', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Concrete pool', 'Fiberglass', 'Renovation'] }],
    [{ name: 'Excavation & Steel', trade: 'Concreting', rate: 25000, unit: 'item', duration: 3, description: 'Excavate and steel fix' },
     { name: 'Shell Construction', trade: 'Concreting', rate: 30000, unit: 'item', duration: 3, description: 'Shotcrete/gunite shell' },
     { name: 'Tile & Coping', trade: 'Tiling', rate: 8000, unit: 'item', duration: 2, description: 'Waterline tile and coping' },
     { name: 'Equipment & Finish', trade: 'Plumbing', rate: 12000, unit: 'item', duration: 2, description: 'Pump, filter, interior finish' }],
    [{ description: 'Pool Equipment', allowance: 5000, unit: 'allowance' }],
    ['Pool shell construction', 'Equipment installation', 'Compliance fencing (separate)'],
    ['Pool fencing', 'Landscaping', 'Heating'],
    [{ categoryId: 'fencing', type: 'auto' }, { categoryId: 'electrical', type: 'auto' }, { categoryId: 'landscaping', type: 'suggested' }],
    10, 'new_build',
  ),

  cat('roofRepairs', '🏠 Roofing — Repairs', 'roofRepairs', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Leak repair', 'Flashing', 'Ridge capping'] }],
    [{ name: 'Inspection & Repair', trade: 'Roofing', rate: 650, unit: 'item', duration: 0.5, description: 'Diagnose and repair' }],
    [],
    ['Leak diagnosis and repair', 'All materials'],
    ['Full re-roof', 'Structural repairs'],
    [{ categoryId: 'roofing', type: 'suggested' }],
  ),

  cat('guttersFascia', '🏠 Gutters & Fascia', 'guttersFascia', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Full replace', 'Partial repair', 'Downpipes'] }],
    [{ name: 'Remove Old', trade: 'Roofing', rate: 25, unit: 'linear', duration: 1, description: 'Remove existing gutter/fascia' },
     { name: 'Install New', trade: 'Roofing', rate: 75, unit: 'linear', duration: 2, description: 'Supply and install new' }],
    [],
    ['Removal and disposal of old', 'New Colorbond supply and install'],
    ['Roofing repairs', 'Painting'],
    [{ categoryId: 'roofing', type: 'suggested' }],
  ),

  cat('insulation', '🛡️ Insulation', 'insulation', 'specialty',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Wall', 'Ceiling', 'Underfloor', 'Acoustic'] }],
    [{ name: 'Installation', trade: 'Carpentry', rate: 35, unit: 'area', duration: 1, description: 'Install bulk/batt insulation' }],
    [],
    ['Supply and installation', 'Code-compliant R-values'],
    ['Making good linings'],
    [{ categoryId: 'ceilings', type: 'suggested' }],
  ),

  catX('fireSafety', '🔥 Fire & Safety', 'fireSafety', 'specialty', 'compliance',
    [
      { id: 'itemType', label: 'Compliance item', type: 'select', options: [
        'Smoke alarm — 240V hardwired interconnected',
        'Smoke alarm — 10yr lithium interconnected',
        'Fire door — 60/30/30 rated',
        'Fire door — 90/60/30 rated',
        'BAL assessment & report',
      ] },
      { id: 'count', label: 'How many?', type: 'number' },
      { id: 'interconnect', label: 'Interconnect to existing system?', type: 'select', options: ['Yes — extend existing', 'No — standalone'],
        dependsOn: { questionId: 'itemType', values: ['Smoke alarm — 240V hardwired interconnected', 'Smoke alarm — 10yr lithium interconnected'] } },
    ],
    [
      // Compliance pricing is fixed per unit — engine multiplies stage rate × answers.count.
      { name: 'Supply & install', trade: 'Electrical', rate: 240, unit: 'item', duration: 0.5, description: 'Per AS3786 — supply, install, test' },
    ],
    [],
    ['AS3786 / AS1530 compliance certificate', 'Supply, install, test, and tag', 'Battery backup where applicable'],
    ['Fire sprinkler systems', 'Detection panels / monitored alarms', 'Patching & painting after install'],
    [],
    { dimensionMode: 'none', supportsPcItems: false, contingency: 5, workType: 'maintenance' },
  ),

  cat('accessibility', '♿ Accessibility / SDA', 'accessibility', 'specialty',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Ramps', 'Grab rails', 'NDIS modifications', 'Widened doors'] }],
    [{ name: 'Ramp Construction', trade: 'Carpentry', rate: 350, unit: 'linear', duration: 1, description: 'Build access ramp' },
     { name: 'Grab Rails & Modifications', trade: 'Carpentry', rate: 250, unit: 'item', duration: 0.5, description: 'Install rails and modify' }],
    [],
    ['AS1428 compliance', 'All materials and labour'],
    ['Engineering certification', 'Structural modifications'],
    [],
  ),

  cat('heritage', '🏛️ Heritage', 'heritage', 'specialty',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Period features', 'Heritage compliance', 'Restoration'] }],
    [{ name: 'Heritage Assessment', trade: 'Carpentry', rate: 2500, unit: 'item', duration: 5, description: 'Heritage consultant report' },
     { name: 'Restoration Works', trade: 'Carpentry', rate: 350, unit: 'area', duration: 5, description: 'Period-accurate restoration' }],
    [],
    ['Heritage-compliant materials', 'Period-accurate workmanship'],
    ['Heritage permit fees', 'Specialist trades'],
    [],
  ),

  cat('rendering', '🔇 Rendering', 'rendering', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Cement render', 'Texture coat', 'Acrylic'] }],
    [{ name: 'Surface Prep', trade: 'Carpentry', rate: 25, unit: 'area', duration: 1, description: 'Clean and prepare' },
     { name: 'Render Application', trade: 'Carpentry', rate: 85, unit: 'area', duration: 2, description: 'Supply and apply render' }],
    [],
    ['Surface preparation', 'Quality render finish'],
    ['Painting (separate)', 'Structural repairs'],
    [{ categoryId: 'painting', type: 'suggested' }, { categoryId: 'cladding', type: 'suggested' }],
  ),

  cat('cladding', '🧱 Cladding', 'cladding', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Weatherboard', 'Fibre cement', 'Metal'] }],
    [{ name: 'Wall Prep', trade: 'Carpentry', rate: 35, unit: 'area', duration: 1, description: 'Prepare wall surface' },
     { name: 'Cladding Install', trade: 'Carpentry', rate: 120, unit: 'area', duration: 3, description: 'Supply and fix cladding' }],
    [],
    ['Sarking and wrap', 'Cladding supply and install'],
    ['Insulation (separate)', 'Painting (if required)'],
    [{ categoryId: 'insulation', type: 'suggested' }, { categoryId: 'painting', type: 'suggested' }],
  ),

  cat('acoustic', '🔇 Acoustic', 'acoustic', 'specialty',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Soundproofing', 'Party wall', 'Acoustic ceiling'] }],
    [{ name: 'Acoustic Treatment', trade: 'Carpentry', rate: 95, unit: 'area', duration: 2, description: 'Install acoustic insulation and systems' }],
    [],
    ['Acoustic insulation', 'Sound-dampening systems'],
    ['Structural decoupling'],
    [{ categoryId: 'insulation', type: 'suggested' }],
  ),

  cat('smartHome', '📡 Smart Home & Data', 'smartHome', 'specialty',
    [{ id: 'type', label: 'Type', type: 'select', options: ['CCTV', 'Intercom', 'Network', 'Automation'] }],
    [{ name: 'System Install', trade: 'Electrical', rate: 2500, unit: 'item', duration: 2, description: 'Install smart home system' }],
    [{ description: 'Smart Hub/Controller', allowance: 800, unit: 'item' }],
    ['Equipment and installation', 'Network configuration'],
    ['Structural cabling runs'],
    [{ categoryId: 'electrical', type: 'auto' }],
  ),

  cat('brickwork', '🧱 Brickwork & Masonry', 'brickwork', 'structural',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Brick repair', 'Repointing', 'Block wall'] }],
    [{ name: 'Brickwork', trade: 'Carpentry', rate: 180, unit: 'area', duration: 3, description: 'Lay brick or block work' }],
    [],
    ['Quality brickwork', 'Matching existing where required'],
    ['Engineering for structural walls', 'Footings'],
    [{ categoryId: 'structural', type: 'suggested' }],
  ),
];

/* ── Master Registry ── */
import { CORE_CATEGORIES } from './core';
export const ALL_CATEGORIES: WorkCategory[] = [...CORE_CATEGORIES, ...EXTENDED_CATEGORIES];

export const CATEGORY_MAP: Record<string, WorkCategory> = {};
ALL_CATEGORIES.forEach(c => { CATEGORY_MAP[c.id] = c; });

export const CATEGORY_GROUPS_MAP: Record<string, string> = {
  wet: 'Wet Areas & Interiors',
  structural: 'Structural & Extensions',
  external: 'External Works',
  trades: 'Trades & Services',
  specialty: 'Specialty',
};

export function getCategoryById(id: string): WorkCategory | undefined {
  return CATEGORY_MAP[id];
}

export function searchCategories(query: string): WorkCategory[] {
  const q = query.toLowerCase();
  return ALL_CATEGORIES.filter(c =>
    c.label.toLowerCase().includes(q) ||
    c.id.toLowerCase().includes(q) ||
    c.stages.some(s => s.trade.toLowerCase().includes(q) || s.name.toLowerCase().includes(q)),
  );
}